# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce7a5dc085b00fd9babff4b1e56cb9ca93f8e26ca9dee61f0902b3da6cefbe540ae0d736ee592d52af1514a562be2ab024b63b9905a0a039df8fd68948a95f94

test:
  secret_key_base: 8541e56af0c203655f18cef5b3e1f33506115d3a8173a2cd3e24834440aae165031259efd8172d54a2ea7147fb9ce3f0d54da01e803bfa56eee38ca53b8cd177

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
